models_directory = "models/"
dataset_directory = "dataset/"
hf_token_path = "../../hf-token.txt"

# model_name="google/gemma-3-4b-it"
# model_name="vikhyatk/moondream2"
# model_name="llava-hf/llava-1.5-7b-hf"
# model_name="llava-hf/llava-1.5-13b-hf"
model_name="llava-hf/llava-v1.6-vicuna-13b-hf"
dataset=dataset_directory+"val2014"
dataset_json=dataset_directory+"val.json"