frequencies:
  - Hourly

models:
  - type: Chronos
    repo_id: amazon/chronos-t5-tiny
    alias: chronos_tiny
    batch_size: 1

  # - type: Chronos
  #   repo_id: amazon/chronos-t5-mini
  #   alias: chronos_mini
  #   batch_size: 1

  # - type: Chronos
  #   repo_id: amazon/chronos-t5-small
  #   alias: chronos_small
  #   batch_size: 1

  # - type: Chronos
  #   repo_id: amazon/chronos-t5-base
  #   alias: chronos_base
  #   batch_size: 1

  # - type: Chronos
  #   repo_id: amazon/chronos-t5-large
  #   alias: chronos_large
  #   batch_size: 1


  # - type: Moirai
  #   repo_id: Salesforce/moirai-16.0-R-small
  #   alias: Moirai_Small
  #   batch_size: 16

  # - type: Moirai
  #   repo_id: Salesforce/moirai-16.0-R-base
  #   alias: Moirai_Base
  #   batch_size: 16

  # - type: Moirai
  #   repo_id: Salesforce/moirai-16.0-R-large
  #   alias: Moirai_Large
  #   batch_size: 16

  # - type: LagLlama
  #   repo_id: time-series-foundation-models/Lag-Llama
  #   alias: LagLlama
  #   batch_size: 16

  # - type: TimesFM
  #   repo_id: google/timesfm-16.0-200m
  #   alias: TimesFM-200m
  #   batch_size: 16

  # - type: TimesFM
  #   repo_id: google/timesfm-16.0-500m
  #   alias: TimesFM-500m
  #   batch_size: 16