# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from device.proto import edge_runtime_pb2 as device_dot_proto_dot_edge__runtime__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device/proto/edge_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/serving.device.EdgeRuntime/Infer',
                request_serializer=device_dot_proto_dot_edge__runtime__pb2.InferRequest.SerializeToString,
                response_deserializer=device_dot_proto_dot_edge__runtime__pb2.InferResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/serving.device.EdgeRuntime/Control',
                request_serializer=device_dot_proto_dot_edge__runtime__pb2.ControlRequest.SerializeToString,
                response_deserializer=device_dot_proto_dot_edge__runtime__pb2.ControlResponse.FromString,
                _registered_method=True)


class EdgeRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=device_dot_proto_dot_edge__runtime__pb2.InferRequest.FromString,
                    response_serializer=device_dot_proto_dot_edge__runtime__pb2.InferResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=device_dot_proto_dot_edge__runtime__pb2.ControlRequest.FromString,
                    response_serializer=device_dot_proto_dot_edge__runtime__pb2.ControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serving.device.EdgeRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serving.device.EdgeRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serving.device.EdgeRuntime/Infer',
            device_dot_proto_dot_edge__runtime__pb2.InferRequest.SerializeToString,
            device_dot_proto_dot_edge__runtime__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serving.device.EdgeRuntime/Control',
            device_dot_proto_dot_edge__runtime__pb2.ControlRequest.SerializeToString,
            device_dot_proto_dot_edge__runtime__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
